### ISSUE TITLE
Pin requirements.txt libraries

### ISSUE THREAD

**Issue by deadbits** [davidonzo/apiosintDS#1]
Adding the version numbers to requirements.txt should avoid any conflicting package versions from other Python apps folks have installed.
Personally, I'm pretty hesitant to install this repo since I don't want it to break any other existing apps.

**Comment by davidonzo** [comment]
Dear Adam,
You are right, thank you very much.

Will be fixed soon. This evening at least.
My mistake, sorry.

I'll close the issue after pushing the new file.

**Comment by davidonzo** [comment]
Dear Adam,
requirements.txt has been pinned as required.

The issue will remain opened for a while for verification and community testing purpose.

Thanks for your contribution! Very appreciated.
