### ISSUE TITLE
Module uses root logger rather than a module logger

### ISSUE THREAD

**Issue by ostefano** [davidonzo/apiosintDS#2]
This module configures the root logger rather than the module logger:

> logging.basicConfig(format='%(levelname)s: %(message)s')

When this module is used by another project (for example misp-modules), this has the side effect of modifying other potentially custom-made loggers.

This is the reason why when launching `misp-modules', each line is printed twice.

**Comment by davidonzo** [comment]
Ciao Stefano,

Can you provide me a practical example of the issue?
Thanks in advance.

**Comment by ostefano** [comment]
When the module `apiosintDS` is used by `misp-modules` (https://github.com/MISP/misp-modules), the module hijacks the root logger even though the main application dictating how the root logger should behave is `misp-modules`. This has the side-effect, for example, of duplicating every line in the logs if both `misp-modules` and `apiosintDS` decide to configure their own stream handlers (which is done via the `basicConfig` instruction). Alternatively if `misp-modules` decides not to log anything, this gets overridden by `apiosintDS`. 

To reproduce the issue install `misp-modules` and execute it, or alternatively, create a new python application with your own configuration of the stream handlers and formatters attached to the root logger, and then import `apiosintDS`.

The fix here is to have `apiosintDS` its own logger `logger = logging.getLogger(_name_)` and remove the initialization of the root logger from all modules being imported; you can then move the initialization of the root logger to within the scope of the main function so it's not executed every time you import the package. Then the main function itself should be moved to a standalone script importing the `apiosintDS` module, and installed inside the bin directory by setuptools.

I understand this is a non-trivial change-set.

**Comment by davidonzo** [comment]
Issue solved.
Please read the changelog.
Thank you very much and please, reopen this issue if you think something is to be adjusted.
https://github.com/davidonzo/apiosintDS/blob/master/CHANGELOG.rst

**Comment by ostefano** [comment]
Perfect, I can confirm the issue is now solved (no double logging anymore if misp-modules installs the latest version of the library).

**Comment by davidonzo** [comment]
Thanks for the feedback!
